### ISSUE TITLE
为什么还是跑服务器带宽？

### ISSUE THREAD

**Issue by LIUBANGJIAN** [Akimio521/AutoFilm#10]
按照教材设置，emby播放为什么还是跑服务器带宽？

**Comment by Akimio521** [comment]
请详细阅读博客教程

**Comment by sjtuross** [comment]
https://emby.media/community/index.php?/topic/75314-strm-directly-from-the-source/

按照Emby官方成员的说法，客户端是不能直接播放strm里面的直链的，否则违反app商店政策。

这个项目说的不受服务器带宽限制，是仅针对Jellyfin吗？

**Comment by Akimio521** [comment]
> https://emby.media/community/index.php?/topic/75314-strm-directly-from-the-source/
> 
> 按照Emby官方成员的说法，客户端是不能直接播放strm里面的直链的，否则违反app商店政策。
> 
> 这个项目说的不受服务器带宽限制，是怎么测试的？貌似博客里面没有

博客原文档被我删了，可能新文档里没有写，原版emby服务器是不支持直接推送strm的，需要额外加一个nginx拦截请求，原版jellyfin是可以直接推送strm的以达到节省jellyfin服务器流量的目的
[[发现] plex, emby, jellyfin对直链的处理方式](https://machbbs.com/hostloc/465433)
> strm即直链。
>plex：无法识别，处理不了
>emby：服务器下载直链视频，并提交客户端进行流控， 会走服务器流量
>jellyfin：直接提交给客户端播放器，服务器啥事不干，不走服务器流量
