### ISSUE TITLE
本程序会计划做成docker吗

### ISSUE THREAD

**Issue by tt555-1** [Akimio521/AutoFilm#13]
自行安装本程序有一定的难度，请问作者，有计划将本程序做成docker吗，这样NAS用户，都可以使用，会很方便的。

**Comment by Akimio521** [comment]
目前我的解决方法就是用nas的定时任务定时扫描。虽然之前有适配docker的计划，但搁置了，因为当前这个脚本的设计方式不适合在docker内长期运行，要使用必须进入容器内手动执行命令，其实比定时任务的执行模式更加麻烦，而且docker只是提供了一个py环境不如手动安装一下py，以后有时间我学一学web开发再考虑正式适配docker吧

**Comment by yating1022** [comment]
> 目前我的解决方法就是用nas的定时任务定时扫描。虽然之前有适配docker的计划，但搁置了，因为当前这个脚本的设计方式不适合在docker内长期运行，要使用必须进入容器内手动执行命令，其实比定时任务的执行模式更加麻烦，而且docker只是提供了一个py环境不如手动安装一下py，以后有时间我学一学web开发再考虑正式适配docker吧

如果做成docker的话，对于一些nas设备可能会更好用一点，比如我用的群晖，我执行命令行老是各种问题

**Comment by Akimio521** [comment]
> > 目前我的解决方法就是用nas的定时任务定时扫描。虽然之前有适配docker的计划，但搁置了，因为当前这个脚本的设计方式不适合在docker内长期运行，要使用必须进入容器内手动执行命令，其实比定时任务的执行模式更加麻烦，而且docker只是提供了一个py环境不如手动安装一下py，以后有时间我学一学web开发再考虑正式适配docker吧
> 
> 
> 
> 如果做成docker的话，对于一些nas设备可能会更好用一点，比如我用的群晖，我执行命令行老是各种问题

目前AutoFilm就算做成docker也是需要进入容器内部的命令行进行操作的，等待有时间我重构一下项目吧
