### ISSUE TITLE
请求添加同步删除参数

### ISSUE THREAD

**Issue by ironstress** [Akimio521/AutoFilm#15]
webdav删除后的文件夹后, 以相同参数再次运行, 原先已有的.strm .nfo 图片等文件不会同步删除

**Comment by Akimio521** [comment]
对，程序是增量式的不是同步式的

**Comment by qcmoke** [comment]
同需要

**Comment by Akimio521** [comment]
该功能已实现。The feature is achieve.
Thanks @Chesyre contribution in #65
