### ISSUE TITLE
请确保当前季度番剧文件夹存在

### ISSUE THREAD

**Issue by kai456789** [Akimio521/AutoFilm#20]
使用巴哈姆特动画疯Strm 出現下列問題 
【INFO】2024-03-05 17:21:27,620 - bahastrm - Baha-Strm定时任务创建成功：*/20 22,23,0,1 * * *
【INFO】2024-03-05 17:21:27,621 - bahastrm - Baha-Strm服务启动，立即运行一次
【WARNING】2024-03-05 17:21:30,694 - bahastrm - 未获取到文件信息，3秒后重试 ...
【WARNING】2024-03-05 17:21:33,726 - bahastrm - 未获取到文件信息，3秒后重试 ...
【WARNING】2024-03-05 17:21:36,756 - bahastrm - 未获取到文件信息，3秒后重试 ...
【WARNING】2024-03-05 17:21:39,757 - bahastrm - https://aniopen.an-i.workers.dev/ 请确保当前季度番剧文件夹存在

**Comment by Akimio521** [comment]
与该项目无关
