### ISSUE TITLE
关于目录格式不能够进行媒体库扫描

### ISSUE THREAD

**Issue by q2051839** [Akimio521/AutoFilm#22]
如果我添加了超过1个的WEBDAV地址，比如
webdav:
   movie:
    url: http://127.0.0.1:5244/dav/onedriver/movie/
    username: admin
    password: x
   show:
    url: http://127.0.0.1:5244/dav/onedriver/show/
    username: admin
    password: x
然后他的目录格式就会变成
![image](https://github.com/Akimio521/AutoFilm/assets/38458888/304a6a25-4e4c-48b4-966b-708205668b6b)
只有奇怪的格式。这样在jellyfin扫描的时候，就无法分开了啊。就会被嵌套扫描。不能够每一个webdav地址都可以指定输出到某一个文件夹么。还是有我不知道的写法，我在论坛没有找到相关配置。

**Comment by q2051839** [comment]
临时的解决方案，让第一条信息是个废目录。例如
webdav:
   test:
    url: http://127.0.0.1:5244/dav/onedriver/test/
    username: admin
    password: xx
   show:
    url: http://127.0.0.1:5244/dav/onedriver/show/
    username: admin
    password: xx
   movie:
    url: http://127.0.0.1:5244/dav/onedriver/movie/
    username: admin
    password: xx
![image](https://github.com/Akimio521/AutoFilm/assets/38458888/251bdb51-edb8-4d80-bfe6-709f1102ddc3)
之后他就会以想象中的格式进行目录作业了。也可以正常进行扫描。而且第一次配置的时候。主目录还出现了其他WEBDAV的内容很奇怪的BUG没有留图，这样解决暂时解决其实很好。

**Comment by q2051839** [comment]
然后新版本获取的图片信息也是错的，我尝试复制到本地。是不能打开的损坏文件。旧版本工作正常。回退了。

**Comment by Akimio521** [comment]
[AutoFilm-v1.0.0](https://github.com/Akimio521/AutoFilm/releases/tag/v1.0.0)是正常的吗
