### ISSUE TITLE
没有列出错误日志，也没有生成strm

### ISSUE THREAD

**Issue by 5536086** [Akimio521/AutoFilm#26]
本地指定目录里面一直没有生成strm文件
`autofilm  | 正在执行主程序...
autofilm  | [2024-05-11 16:40:58,276][INFO]<module>:当前的APP版本是：v1.0.1
autofilm  | [2024-05-11 16:40:58,277][INFO]<module>:配置文件路径：config/config.yaml
autofilm  | [2024-05-11 16:40:58,279][INFO]__init__:输出目录：/opt/media/；list_files线程数：3；processing_file线程数：8
autofilm  | [2024-05-11 16:40:58,279][INFO]run:开始生成[迪士尼动漫]Webdav服务器的Strm文件；剩余0个Webdav服务器未进行
autofilm  | [2024-05-11 16:40:58,280][WARNING]get_config_value:Alist令牌token读取错误，默认关闭，错误信息：'token'
`

但是我并没有填写token，这个是固定报错的，后面没有任何日志内容了，也没有生成strm文件

**Comment by 5536086** [comment]
刚开始用的docker版的，无法生成，重新用py版的，可以生成，但是生成的strm文件无法播放，仔细看了下里面的文件连接，发现没有sign和参数，因此直接打开是401错误，不知如何解决，也尝试着使用token来生成，还是一样的结果。

**Comment by Winnie0408** [comment]
项目当前的`autofilm.py`文件中有一处错误，会导致无法读取配置文件中的`token`信息，辛苦您手动修改下：

修改位置：`autofilm.py`的第62~66行
修改前：
```
    def run(self) -> None:
        webdav_datas = self.get_config_value("webdav", default_value={}, error_message="Webdav服务器列表读取失败")
        if webdav_datas:
            logging.debug("webdav列表加载成功")
            round = 1
            for key, value in webdav_datas.items():
                logging.info(f"开始生成[{key}]Webdav服务器的Strm文件；剩余{(len(webdav_datas) - round)}个Webdav服务器未进行")
                try:
                    url = value["url"]
                    username = value["username"]
                    password = value["password"]
                except Exception as e:
                    logging.error(f"Webdav服务器账号密码地址读取错误，错误信息：{str(e)}")
                else:
                    token = self.get_config_value("token", default_value="", error_message="Alist令牌token读取错误，默认关闭")

                    self.urls_queue.put(url)
```

修改后：
```
    def run(self) -> None:
        webdav_datas = self.get_config_value("webdav", default_value={}, error_message="Webdav服务器列表读取失败")
        if webdav_datas:
            logging.debug("webdav列表加载成功")
            round = 1
            for key, value in webdav_datas.items():
                logging.info(f"开始生成[{key}]Webdav服务器的Strm文件；剩余{(len(webdav_datas) - round)}个Webdav服务器未进行")
                try:
                    url = value["url"]
                    username = value["username"]
                    password = value["password"]
                    token = value.get("token", "")
                except Exception as e:
                    logging.error(f"Webdav服务器账号密码地址读取错误，错误信息：{str(e)}")
                else:
                    self.urls_queue.put(url)

```

**Comment by 5536086** [comment]
按要求填写了Alist令牌token，生成的地址没有sign和参数，无法播放，401报错，很奇怪
![1](https://github.com/Akimio521/AutoFilm/assets/20472307/8eb2cf24-53d4-4fb9-85f2-a5019a7d2fd8)

**Comment by Winnie0408** [comment]
> 按要求填写了Alist令牌token，生成的地址没有sign和参数，无法播放，401报错，很奇怪 ![1](https://private-user-images.githubusercontent.com/20472307/329838662-8eb2cf24-53d4-4fb9-85f2-a5019a7d2fd8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzEwMzIsIm5iZiI6MTcxNTUzMDczMiwicGF0aCI6Ii8yMDQ3MjMwNy8zMjk4Mzg2NjItOGViMmNmMjQtNTNkNC00ZmI5LTg1ZjItYTUwMTlhN2QyZmQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE2MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZGU0MThjYjU0MDM5MTMwOTY5NTM4MDA1YmJkZWE2ZDYzODFhMjE5NTA1NTM1MDllNjMyYjNjNzJlNzc3NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dp-JQ4LvqmOxtmPySHNv5bQSFS9uVbGlimrXGoGHYsg)

修改`autofilm.py`文件中的代码后，生成的地址还是没有sign参数吗？
需要把之前生成的strm文件全部删除，再重新生成哈；程序运行时，若检测到同名文件，会`跳过`，而不是`覆盖`。

**Comment by Winnie0408** [comment]
> > > 按要求填写了Alist令牌token，生成的地址没有sign和参数，无法播放，401报错，很奇怪 ![1](https://private-user-images.githubusercontent.com/20472307/329838662-8eb2cf24-53d4-4fb9-85f2-a5019a7d2fd8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzEwMzIsIm5iZiI6MTcxNTUzMDczMiwicGF0aCI6Ii8yMDQ3MjMwNy8zMjk4Mzg2NjItOGViMmNmMjQtNTNkNC00ZmI5LTg1ZjItYTUwMTlhN2QyZmQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE2MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZGU0MThjYjU0MDM5MTMwOTY5NTM4MDA1YmJkZWE2ZDYzODFhMjE5NTA1NTM1MDllNjMyYjNjNzJlNzc3NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dp-JQ4LvqmOxtmPySHNv5bQSFS9uVbGlimrXGoGHYsg)
> > 
> > 修改`autofilm.py`文件中的Python代码后，生成的地址还是没有sign参数吗？ 需要把之前生成的strm文件全部删除，再重新生成哈；程序运行时，若检测到同名文件，会`跳过`，而不是`覆盖`。
> 
> 对的，不管怎么弄都没有sign和参数

看看您的配置文件（将重要信息做部分打码处理），修改后的`autofilm.py`文件，以及程序加参数`--log_level DEBUG`运行时的输出信息呢？

**Comment by Akimio521** [comment]
> 按要求填写了Alist令牌token，生成的地址没有sign和参数，无法播放，401报错，很奇怪
> 
> ![1](https://github.com/Akimio521/AutoFilm/assets/20472307/8eb2cf24-53d4-4fb9-85f2-a5019a7d2fd8)
> 
> 

浏览器访问这个url可以正确下载吗mkv吗

**Comment by 5536086** [comment]
> > 按要求填写了Alist令牌token，生成的地址没有sign和参数，无法播放，401报错，很奇怪
> > ![1](https://private-user-images.githubusercontent.com/20472307/329838662-8eb2cf24-53d4-4fb9-85f2-a5019a7d2fd8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzAzMzUsIm5iZiI6MTcxNTU3MDAzNSwicGF0aCI6Ii8yMDQ3MjMwNy8zMjk4Mzg2NjItOGViMmNmMjQtNTNkNC00ZmI5LTg1ZjItYTUwMTlhN2QyZmQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAzMTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMzMxYjNiMTIyNDJiYjU5OTU1NjU5YmI1NTY4NTk3ZjFlYzg5MzQ1MGVkZTgzYjIxYTBhYzZhYjNkMzEzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RiefWv_PTiOc5OdK46OVLTMFHnhTjjEpAEc_tcetZGk)
> 
> 浏览器访问这个url可以正确下载吗mkv吗

不能的，401错误，浏览下载都是带有sign和参数的，没有sign和参数就会401错误

**Comment by 5536086** [comment]
> > > > 按要求填写了Alist令牌token，生成的地址没有sign和参数，无法播放，401报错，很奇怪 ![1](https://private-user-images.githubusercontent.com/20472307/329838662-8eb2cf24-53d4-4fb9-85f2-a5019a7d2fd8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzEwMzIsIm5iZiI6MTcxNTUzMDczMiwicGF0aCI6Ii8yMDQ3MjMwNy8zMjk4Mzg2NjItOGViMmNmMjQtNTNkNC00ZmI5LTg1ZjItYTUwMTlhN2QyZmQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE2MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZGU0MThjYjU0MDM5MTMwOTY5NTM4MDA1YmJkZWE2ZDYzODFhMjE5NTA1NTM1MDllNjMyYjNjNzJlNzc3NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dp-JQ4LvqmOxtmPySHNv5bQSFS9uVbGlimrXGoGHYsg)
> > > 
> > > 
> > > 修改`autofilm.py`文件中的Python代码后，生成的地址还是没有sign参数吗？ 需要把之前生成的strm文件全部删除，再重新生成哈；程序运行时，若检测到同名文件，会`跳过`，而不是`覆盖`。
> > 
> > 
> > 对的，不管怎么弄都没有sign和参数
> 
> 看看您的配置文件（将重要信息做部分打码处理），修改后的`autofilm.py`文件，以及程序加参数`--log_level DEBUG`运行时的输出信息呢？

![配置文件](https://github.com/Akimio521/AutoFilm/assets/20472307/c93e59bd-7d22-4a0e-bc97-a076080f5ae8)
![修改后](https://github.com/Akimio521/AutoFilm/assets/20472307/506b792c-f383-4b22-9114-a9d783ce75c2)
![日志](https://github.com/Akimio521/AutoFilm/assets/20472307/1246a122-5125-4a74-ab6a-9a1ccd332444)

**Comment by Winnie0408** [comment]
> > > > > 按要求填写了Alist令牌token，生成的地址没有sign和参数，无法播放，401报错，很奇怪 ![1](https://private-user-images.githubusercontent.com/20472307/329838662-8eb2cf24-53d4-4fb9-85f2-a5019a7d2fd8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzEwMzIsIm5iZiI6MTcxNTUzMDczMiwicGF0aCI6Ii8yMDQ3MjMwNy8zMjk4Mzg2NjItOGViMmNmMjQtNTNkNC00ZmI5LTg1ZjItYTUwMTlhN2QyZmQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE2MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZGU0MThjYjU0MDM5MTMwOTY5NTM4MDA1YmJkZWE2ZDYzODFhMjE5NTA1NTM1MDllNjMyYjNjNzJlNzc3NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dp-JQ4LvqmOxtmPySHNv5bQSFS9uVbGlimrXGoGHYsg)
> > > > 
> > > > 
> > > > 修改`autofilm.py`文件中的Python代码后，生成的地址还是没有sign参数吗？ 需要把之前生成的strm文件全部删除，再重新生成哈；程序运行时，若检测到同名文件，会`跳过`，而不是`覆盖`。
> > > 
> > > 
> > > 对的，不管怎么弄都没有sign和参数
> > 
> > 
> > 看看您的配置文件（将重要信息做部分打码处理），修改后的`autofilm.py`文件，以及程序加参数`--log_level DEBUG`运行时的输出信息呢？
> 
> ![配置文件](https://private-user-images.githubusercontent.com/20472307/329912376-c93e59bd-7d22-4a0e-bc97-a076080f5ae8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTYxMjMsIm5iZiI6MTcxNTYxNTgyMywicGF0aCI6Ii8yMDQ3MjMwNy8zMjk5MTIzNzYtYzkzZTU5YmQtN2QyMi00YTBlLWJjOTctYTA3NjA4MGY1YWU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE1NTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YThkNjJhYzI5ZDJiZDUwZWVlMzAzYWYwMzc0ZmRmMTZlMzRmOWVmMDYyNzdkN2IzOTM4ZDIxZjk1ZjMxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XEZaHQhIcm661iVc-AUMIzZcWTaXyRA_EjvpwltriQg)
> 
> ![修改后](https://private-user-images.githubusercontent.com/20472307/329912401-506b792c-f383-4b22-9114-a9d783ce75c2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTYxMjMsIm5iZiI6MTcxNTYxNTgyMywicGF0aCI6Ii8yMDQ3MjMwNy8zMjk5MTI0MDEtNTA2Yjc5MmMtZjM4My00YjIyLTkxMTQtYTlkNzgzY2U3NWMyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE1NTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ODhmNmQ3NGVhNjZkOTJmZmE0M2E5MjkzMjIzYzFkNjAyNzdiMWEwMDhhM2I2NTI3M2IxOTYxNjliMDVkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n7j-mvIfUPNuG81H1A0dksQImhg1YHdIE_t6LGUAfTs)
> 
> ![日志](https://private-user-images.githubusercontent.com/20472307/329912767-2ad33920-f30a-4eb9-8465-6e205c0130f3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTYxMjMsIm5iZiI6MTcxNTYxNTgyMywicGF0aCI6Ii8yMDQ3MjMwNy8zMjk5MTI3NjctMmFkMzM5MjAtZjMwYS00ZWI5LTg0NjUtNmUyMDVjMDEzMGYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE1NTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNmQ5NjYyZjVmZWZiNjBiZWExMmI0M2Y5YTYwNmQ2YmYwMTM1YzQzYzA5ZTVjMDVlNjAzZGMwM2VkZGEwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.leenC-S5hQ7v3jzv3vrGbhZk87lBxTYSNtoG_OZvfYM)


您配置文件中的`token`配置项被注释了，把`token`所在行行首的`#`号删除，删除已生成的strm文件，再重新运行程序试试呢？

![image](https://github.com/Akimio521/AutoFilm/assets/42741874/05c907c7-30f8-459c-88a1-e832dd7b9256)

**Comment by Akimio521** [comment]
目前 v1.0.2-1 已经修复 token 问题
