### ISSUE TITLE
python报错，请问你们lxml版本是多少？

### ISSUE THREAD

**Issue by zlyz12345** [Akimio521/AutoFilm#27]
zz@iStoreOS:/AutoFilm-1.0.1# python /mnt/-1/AutoFilm-1.0.1/main.py 
Traceback (most recent call last):
  File "/mnt/-1/AutoFilm-1.0.1/main.py", line 5, in <module>
    import autofilm
  File "/mnt/-1/AutoFilm-1.0.1/autofilm.py", line 13, in <module>
    from webdav3.client import Client
  File "/usr/lib/python3.10/site-packages/webdav3/client.py", line 12, in <module>
    import lxml.etree as etree
ModuleNotFoundError: No module named 'lxml.etree'
zz@iStoreOS:/AutoFilm-1.0.1# pip show lxml
Name: lxml
Version: 5.2.2
Summary: Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
Home-page: https://lxml.de/
Author: lxml dev team
Author-email: lxml-dev@lxml.de
License: BSD-3-Clause
Location: /usr/lib/python3.10/site-packages
Requires: 
Required-by: webdavclient3
root@iStoreOS:/mnt/-1/AutoFilm-1.0.1#

**Comment by Akimio521** [comment]
未安装webdavclient3

**Comment by zlyz12345** [comment]
> 未安装webdavclient3

装了的，用的[requirements.txt，这是我pip的依赖，我在想是不是我的有些包版本不对，python是3.10
![image](https://github.com/Akimio521/AutoFilm/assets/49554979/ac7a31f0-19c8-48eb-a65a-d4712953953f)

**Comment by Akimio521** [comment]
我看了我的环境是lxml版本是4.9.4，可以尝试切换，如果还是不行建议使用使用虚拟环境或者docker
