### ISSUE TITLE
新的docker运行出错

### ISSUE THREAD

**Issue by Longxin789** [Akimio521/AutoFilm#28]
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": stat /entrypoint.sh: no such file or directory: unknown.

**Comment by Longxin789** [comment]
直接用的教程的命令

**Comment by Akimio521** [comment]
Dockerfile的entrypoint多了一个/忘记删了，明天再重新构建一个

**Comment by Longxin789** [comment]
> Dockerfile的entrypoint多了一个/忘记删了，已经重新构建一个新镜像，请尝试重新拉取

能拉取但是运行不了，日志报错exec /app/entrypoint.sh: no such file or directory

**Comment by Akimio521** [comment]
已经排查问题，确认是WIndows下的换行符有`\r`导致无法正确运行，已更新镜像
