### ISSUE TITLE
建议增加与本地对比

### ISSUE THREAD

**Issue by gaodyoffice** [Akimio521/AutoFilm#37]
实际使用中发现的。大佬勿怪😁。
1，判断本地是否有.strm，有就跳过，没有就生成。或者增加跳过或覆盖模式。(增加效率)
2，判断图片和字幕与本地大小是否一致，一致就跳过，不一致就覆盖。(有些图片是0kb，图片损坏,需要手动删除，重新运行)
3，刮削完成后触发emby刷新库。(目前设定的每2小时刷库)

**Comment by Akimio521** [comment]
1. v1.1.2已支持
2. 这个问题大概率是网盘的并发性能差导致的，推荐将配置文件中的`async`设置为`False`，并且后续主要添加刮削功能，
3. 这个有关于jellyfin、emby等媒体服务器的API，优先级较低

**Comment by gaodyoffice** [comment]
大佬威武😁
