### ISSUE TITLE
使用alist api后，比以前webdav加载慢了很多

### ISSUE THREAD

**Issue by yonly1314** [Akimio521/AutoFilm#39]
程序每次读取alist列表数据时，很慢，以前webdav的时候，是读一个目录就能开始处理了，现在感觉像是把所有数据加载完后，才开始处理

**Comment by Akimio521** [comment]
我个人觉得速度是变快了，但确实是把所有数据加载完后才开始处理，这个是因为python-alist的缘故，后期可以考虑重写相关alist的api，但是目前暂时没有想法
已经向python-alist反映https://github.com/ChenyangGao/web-mount-packs/issues/24
可能重写完成后也许会采用生成器的方式运行，届时可以便读取目录边处理

**Comment by yonly1314** [comment]
我150T的资源，加载都要花30分钟以上

**Comment by Akimio521** [comment]
资源那么多的话确实不合适使用这种方法，特别占用内存，建议是按目录拆成多个Server或者使用老版本多线程的方式

**Comment by ChenyangGao** [comment]
![IMG_20240703_180720.jpg](https://github.com/Akimio521/AutoFilm/assets/26198875/92620cc2-3e7b-4d3a-be8a-0d5b2245ed62)

你这里自己把整个数据全加载完，才去提交的

不要用那个aysncio.gather了，换用这个

https://docs.python.org/3/library/asyncio-task.html#asyncio.TaskGroup

**Comment by ChenyangGao** [comment]
create_task并不是创建了就运行，需要你当前的函数，用类似await、async for之类的操作交出控制权后才能运行

**Comment by ChenyangGao** [comment]
你可以先改，等我重构完成后，帮你把代码改一下，用更直接的api，直接用我那个模块里面的异步实现

**Comment by Akimio521** [comment]
好的，我研究研究

**Comment by Akimio521** [comment]
> 我150T的资源，加载都要花30分钟以上

最近的版改成了边扫描边生成，可以试一下

**Comment by ChenyangGao** [comment]
<img width="650" alt="截屏2024-07-04 15 00 40" src="https://github.com/Akimio521/AutoFilm/assets/26198875/746313f9-91c9-4761-92ec-d508cfcb5372">
这个await不用加

**Comment by Akimio521** [comment]
> <img alt="截屏2024-07-04 15 00 40" width="650" src="https://private-user-images.githubusercontent.com/26198875/345728961-746313f9-91c9-4761-92ec-d508cfcb5372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzY5MjYsIm5iZiI6MTcyMDA3NjYyNiwicGF0aCI6Ii8yNjE5ODg3NS8zNDU3Mjg5NjEtNzQ2MzEzZjktOTFjOS00NzYxLTkyZWMtZDUwOGNmY2I1MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA3MDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjg0YmZiYTk3MDVjYzk0M2JkYTUxMjAzODAwMTU5ZGRiNzlhZmYwOWU5OGE3MmY1OTAxZDU5NTcwYjFhYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lv02k8IAU7U4K9obHKCND9U76YwxXEpuS-KZDHWXrpc"> 这个await不用加

不加这个await好像会导致不会主动放权，实际上还是先扫描所有目录再进行处理，并不会一边扫描目录一边处理
未加await
![image](https://github.com/Akimio521/AutoFilm/assets/77880495/0304a0a1-d5ad-42db-8acc-c01100064568)
加上await
![image](https://github.com/Akimio521/AutoFilm/assets/77880495/efc3b038-a82d-4cc3-8519-17a289cef8db)

**Comment by Akimio521** [comment]
> 最新的版本，感觉上提升了一点，但不明显

这么写应该只能减少内存占用（大概）可能还是大量的时间花费在等待Alist的API接口的响应上

**Comment by ChenyangGao** [comment]
> > <img alt="截屏2024-07-04 15 00 40" width="650" src="https://private-user-images.githubusercontent.com/26198875/345728961-746313f9-91c9-4761-92ec-d508cfcb5372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzY5MjYsIm5iZiI6MTcyMDA3NjYyNiwicGF0aCI6Ii8yNjE5ODg3NS8zNDU3Mjg5NjEtNzQ2MzEzZjktOTFjOS00NzYxLTkyZWMtZDUwOGNmY2I1MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA3MDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjg0YmZiYTk3MDVjYzk0M2JkYTUxMjAzODAwMTU5ZGRiNzlhZmYwOWU5OGE3MmY1OTAxZDU5NTcwYjFhYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lv02k8IAU7U4K9obHKCND9U76YwxXEpuS-KZDHWXrpc"> 这个await不用加
> 
> 不加这个await好像会导致不会主动放权，实际上还是先扫描所有目录再进行处理，并不会一边扫描目录一边处理 未加await ![image](https://private-user-images.githubusercontent.com/77880495/345731730-0304a0a1-d5ad-42db-8acc-c01100064568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTA0NzgsIm5iZiI6MTcyMDA5MDE3OCwicGF0aCI6Ii83Nzg4MDQ5NS8zNDU3MzE3MzAtMDMwNGEwYTEtZDVhZC00MmRiLThhY2MtYzAxMTAwMDY0NTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEwNDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYTI0NjI1OTRiNjAwYjAwYzdmZjQxMjllYjZlNDVkOTlkMzBjYTg3MmQ1MDkyODk4OTEzNmE2MjYxY2UzOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n0XjcJWL6V2conkbvKTJpmmp74lUzYIpWXrBJ2aAIcA) 加上await ![image](https://private-user-images.githubusercontent.com/77880495/345732219-efc3b038-a82d-4cc3-8519-17a289cef8db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTA0NzgsIm5iZiI6MTcyMDA5MDE3OCwicGF0aCI6Ii83Nzg4MDQ5NS8zNDU3MzIyMTktZWZjM2IwMzgtYTgyZC00Y2MzLTg1MTktMTdhMjg5Y2VmOGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEwNDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOTg4ZDgwODNiY2VlZDM2NzgyYjI2ZjNiNTA5MDFjYjczMjU3YzljYjFmNGM0M2Y3YzVhMDNjNGNmN2RkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mSmFg7Q4KPeGbfE6SnTsW-R5cEWicNlr5x35tjKprFo)

对，确实好像这样，因为这是个同步for循环，等我这两天把新的版本推上去，就可以用async for了，就可以真的不加await了

**Comment by Akimio521** [comment]
其实我觉得现在运行效率挺好的，有些时候并发度太高导致网盘直接不响应，下载出来的文件都是有问题的，还增加了同步下载的模式，目前对于异步生成strm的效率已经挺高了

**Comment by Akimio521** [comment]
可以试试docker pull akimio/autofilm:DEV
注意修改配置文件

**Comment by Akimio521** [comment]
如后续有反馈，再开启此Issue
