### ISSUE TITLE
 可以生成strm文件，但是不全

### ISSUE THREAD

**Issue by blacktea1891** [Akimio521/AutoFilm#40]
感谢这个小项目，用起来可以生成能使用的strm文件。但是文件夹嵌套的只能生成子文件夹的，在根目录的生成不了。
比如这种
![image](https://github.com/Akimio521/AutoFilm/assets/96643293/8d605bf0-6884-4fbc-83f6-1e3c448058f8)

上面的子文件夹可以识别生成，下面根文件夹的识别生成不出来。
解决办法只能再建一个文件夹把根文件夹下的零散的内容都塞到里面了么，还是能再优化下？

**Comment by Akimio521** [comment]
按道理来说应该不会，应该是可以正常遍历的，但我确实没有测试过这种目录结构，这部分我用的是其他人打包好的库，有待进一步测试
每次都能复现吗，还是只有几次不能

**Comment by blacktea1891** [comment]
上午又试了2次，还都是这个情况

**Comment by Akimio521** [comment]
试试docker pull akimio/autofilm:DEV
注意修改配置文件

**Comment by blacktea1891** [comment]
那python环境运行，还是python app/main.py 吗？

**Comment by blacktea1891** [comment]
[INFO]2024-07-08 21:21:24,574 - AutoFilm 启动中，当前的APP版本是：v1.2.0
[INFO]2024-07-08 21:21:24,579 - 检测到 Alist 服务器配置，正在添加至后台任务
[INFO]2024-07-08 21:21:24,641 - 电影已被添加至后台任务

运行好几次，都是停在这里了，然后没有文件生成
配置文件如下
Settings:
  DEV: True                           # 开发者模式(可选，默认 False)

Alist2StrmList:
  - id: 电视剧
    cron: 30 1 * * *                  # 后台定时任务 Crontable 表达式
    url: http://192.168.1.100:5244     # Alist 服务器地址
    username: xxxx                     # Alist 账号
    password: xxxxx              # Alist 密码
    token:                         # AList 未启用签名时，设置为空字符串
    source_dir: /115/电视剧                 # Alist 服务器上文件夹路径
    target_dir: /media/1             # 输出路径
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: False                   # 是否下载字幕文件(可选，默认 False)
    image: False                      # 是否下载图片文件(可选，默认 False)
    nfo: False                        # 是否下载 .nfo 文件(可选，默认 False)
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件(可选，默认 False)
    max_workers: 5                    # 下载文件最大并发数(可选，默认 5)

**Comment by Akimio521** [comment]
因为你配置的是凌晨1:30才生成，时间未到，程序自然阻塞，不会cron表达式可以问一下gpt

**Comment by blacktea1891** [comment]
对不起，我的错。。。

**Comment by Akimio521** [comment]
可以改成`50 21 * * *`这样每天的21:50都会自动运行，如果`overwrite`为`True`那么每次都会尝试重新生成strm和下载图片字幕等信息（如果开启了的话），如果为`False`则是扫描目录有没有新增的文件，对于本地已经存在的文件就不进行操作（增量模式）

**Comment by Akimio521** [comment]
如果不想在后台定时运行，等待运行结束后可以crtl+c（command+c）退出程序

**Comment by blacktea1891** [comment]
明白了，那我要是想后台定时运行，那就用tumx挂在后台就可以了吧？

**Comment by Akimio521** [comment]
都可以，后台运行其实更推荐使用docker的方式部署
