### ISSUE TITLE
新版本代码报错

### ISSUE THREAD

**Issue by liquidsnake9** [Akimio521/AutoFilm#44]
`File "/root/AutoFilm-main/app/main.py", line 27
    logger.info(f"{server["id"]}已被添加至后台任务")
                           ^^
SyntaxError: f-string: unmatched '['
`

**Comment by liquidsnake9** [comment]
> `File "/root/AutoFilm-main/app/main.py", line 27 logger.info(f"{server["id"]}已被添加至后台任务") ^^ SyntaxError: f-string: unmatched '[' `
这个把python升级到3.12解决了，但又有新的报错了
`Traceback (most recent call last):`
`  File "/root/AutoFilm-main/app/main.py", line 13, in <module>`
`    from modules import Alist2Strm`
`  File "/root/AutoFilm-main/app/modules/__init__.py", line 1, in <module>`
`    from .alist2strm import Alist2Strm`
`  File "/root/AutoFilm-main/app/modules/alist2strm/__init__.py", line 1, in <module>`
`    from app.modules.alist2strm.alist2strm import Alist2Strm`
`ModuleNotFoundError: No module named 'app'`
`

**Comment by Akimio521** [comment]
直接git clone整个最新的项目吗

**Comment by Akimio521** [comment]
提示是导包出错，检查`app/main.py`开头处有无
```py
from sys import path
from os.path import dirname
path.append(dirname(dirname(__file__)))
```
不过你运行到下面导入模块这里说明前面setting是正常被导入了，说明是可以找到app这个包的

**Comment by liquidsnake9** [comment]
> 提示是导包出错，检查`app/main.py`开头处有无
> 
> ```python
> from sys import path
> from os.path import dirname
> path.append(dirname(dirname(__file__)))
> ```
> 
> 不过你运行到下面导入模块这里说明前面setting是正常被导入了，说明是可以找到app这个包的

开头的代码存在，分别在ubuntu和windows系统下都试了，都是提示找不到这个包

**Comment by Akimio521** [comment]
找到问题了，你的程序可能在git pull时出现了问题，部分文件并不是最新的
我看到你的提示` from .alist2strm import Alist2Strm`目前最新版本是`from app.modules.alist2strm import Alist2Strm`
保留配置文件，重新git clone整个项目吧，或者使用docker进行部署

**Comment by liquidsnake9** [comment]
> 找到问题了，你的程序可能在git pull时出现了问题，部分文件并不是最新的 我看到你的提示` from .alist2strm import Alist2Strm`目前最新版本是`from app.modules.alist2strm import Alist2Strm` 保留配置文件，重新git clone整个项目吧，或者使用docker进行部署

重新下载code，重新安装必要的包，现在能运行了
