### ISSUE TITLE
生成strm速度变慢了，

### ISSUE THREAD

**Issue by blacktea1891** [Akimio521/AutoFilm#46]
生成strm的速度变慢了，之前10分多钟就好了，现在要快一小时了。而且只有字幕跳过了，每扫描一次就重新生成一次，覆盖模式也设置的false。
![1721383006372](https://github.com/user-attachments/assets/edf8e79b-962a-4270-b1a5-da73b26e3284)
![image](https://github.com/user-attachments/assets/3dcfc69b-ec63-45c1-990d-65ad2073755e)

配置文件设置如下
Settings:
  DEV: True                           # 开发者模式(可选，默认 False)

Alist2StrmList:
  - id: 电影
    cron: 0 */12 * * *                  # 后台定时任务 Crontable 表达式
    url: http://192.168.18.2:5244     # Alist 服务器地址
    username: admin                     # Alist 账号
    password: myalist             # Alist 密码
    token:                      # AList 未启用签名时，设置为空字符串
    source_dir: /115/动画                 # Alist 服务器上文件夹路径
    target_dir: /media/动画            # 输出路径
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: True                   # 是否下载字幕文件(可选，默认 False)
    image: False                      # 是否下载图片文件(可选，默认 False)
    nfo: False                        # 是否下载 .nfo 文件(可选，默认 False)
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件(可选，默认 False)
    max_workers: 5

**Comment by Akimio521** [comment]
之前是指什么时候
可以尝试调高`max_workers`的值以提高效率，但是收到网盘并发的影响

**Comment by blacktea1891** [comment]
上次提issues时，月初，1.2.0版本的时候

**Comment by Akimio521** [comment]
- v1.2.0采用的是python-alist对alist的api进行通信
- v1.2.1，我自己写了alist的api

区别应该是在于token签名这部分，python-alist是应该是采用字符串拼接的方式计算完整的url链接，v1.2.1开始是直接找alist服务器查询当前的签名参数

这样每多出一个文件就需要多发出一次post请求，效率应该会降低，但是也是从这个版本开始可以不用手动输入token，并且可以更加完美处理有过期时间的签名

**Comment by Akimio521** [comment]
试一下最新的版本（python部署需要重新git clone，docker部署使用DEV标签）现在优化了效率，对于已经存在的strm应该也不会生成

**Comment by blacktea1891** [comment]
好的，我试试

**Comment by blacktea1891** [comment]
重生成的问题解决了。

但有个新问题，我这动漫存了不少单独的mka音轨，新版本默认把所有文件都下下来，因为空间有限，全下来空间是不够的。

我看config里新加了一条other_ext:，和这个有关吗？

或者能关闭默认全下载吗，有需要全下载的，再开启。

**Comment by Akimio521** [comment]
默认是只有图片、字幕、nfo的支持，other_ext是方便自定义需要下载的文件的后缀，如果不需要留空

**Comment by blacktea1891** [comment]
![1721694985645](https://github.com/user-attachments/assets/a096c812-1f6a-4bee-b9a5-99f46367a3c3)
又试了一次mka文件还是被下载了。
![微信截图_20240723084343](https://github.com/user-attachments/assets/a03dc0a0-5e74-4954-81a1-a2f27c8a5ceb)

输出目录是看日期是新下的

配置为
  - id: 动画
    cron: 30 8 * * *                  # 后台定时任务 Crontable 表达式
    url: http://192.168.18.3:5244     # Alist 服务器地址
    username: admin                     # Alist 账号
    password: Myalist             # Alist 密码
    token:                         # AList 未启用签名时，设置为空字符串
    source_dir: /115/动画                 # Alist 服务器上文件夹路径
    target_dir: /media/动画             # 输出路径
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: True                   # 是否下载字幕文件(可选，默认 False)
    image: False                      # 是否下载图片文件(可选，默认 False)
    nfo: False                        # 是否下载 .nfo 文件(可选，默认 False)
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件(可选，默认 False)
    other_ext:                  # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）   
    max_workers: 5                    # 下载文件最大并发数(可选，默认 5)

**Comment by Akimio521** [comment]
最新的版本吗，昨天发现other_ext有点问题，修改了一下

**Comment by blacktea1891** [comment]
![微信截图_20240723162215](https://github.com/user-attachments/assets/e6b8e701-3c59-47db-883d-b659da30c727)
下午又试了下，还是会下载

**Comment by Akimio521** [comment]
刚刚确认了问题，更新一下

**Comment by blacktea1891** [comment]
试了下，已经可以了
