### ISSUE TITLE
文件拓展名是大写的，例如MKV、MP4的不能识别

### ISSUE THREAD

**Issue by hanlihanshaobo** [Akimio521/AutoFilm#47]

**Comment by Akimio521** [comment]
最新版本已经修复，docker可以使用DEV标签尝试，或等待后续版本更新

**Comment by hanlihanshaobo** [comment]
能识别了 但是获取过来的不是直链，好像是被压缩过的原文件

**Comment by Akimio521** [comment]
没理解你是什么意思

**Comment by hanlihanshaobo** [comment]
正常获取到的是strm的文件，MKV获取到的还是MKV结尾的文件

**Comment by Akimio521** [comment]
是小写的mkv在本地生成strm，而大写的MKV则是把视频下载到本地这个问题吗

**Comment by hanlihanshaobo** [comment]
是的

**Comment by hanlihanshaobo** [comment]
[WARNING]2024-07-20 12:40:03,355 - 出现错误，错误信息下载失败: 速度与激情7 - Extended Edition (2015) 1080p DTS.MKV，3秒后重试 ...
[WARNING]2024-07-20 12:40:04,328 - 出现错误，错误信息下载失败: 速度与激情6 - Extended Edition (2013) 1080p DTS.MKV，3秒后重试 ...
[WARNING]2024-07-20 12:40:06,328 - 出现错误，错误信息下载失败: 速度与激情5 (2011) 1080p DTS.MKV，3秒后重试 ...
[WARNING]2024-07-20 12:40:07,329 - 出现错误，错误信息下载失败: 速度与激情3：东京漂移 (2006) 1080p DTS.MKV，3秒后重试 ...
[WARNING]2024-07-20 12:40:08,330 - 出现错误，错误信息下载失败: 速度与激情4 (2009) 1080p DTS.MKV，3秒后重试 ...

**Comment by Akimio521** [comment]
已重新提交更新
