### ISSUE TITLE
增加一个周期执行可选项

### ISSUE THREAD

**Issue by FeranyDev** [Akimio521/AutoFilm#49]
不知道为什么我的 cron 总是没法触发，所有希望能够添加另一个触发器 ```scheduler.add_job(Alist2Strm(**server).run, 'interval', seconds=interval)``` 共使用者自行选择。但这样设置首次添加任务的时候并不会执行，需要等一个 interval 周期才会执行。
![图片](https://github.com/user-attachments/assets/5e6579c9-7818-4dea-87b8-0f0faa614146)

**Comment by Akimio521** [comment]
1. 假设现在是`21:05`，那么至少设置cron为`6 21 * * *`才会立刻执行
2. 太多触发方式会增加无意义的结构和判断，增加不必要耦合
3. 如果你的使用方式只是单次运行程序没有后台运行需求，可以直接新开一个脚本引入`Alist2Strm`这个类，创建对象后直接在异步loop中调用`run()`方法
4. 后续版本会考虑增加网页端，届时可以直接通过Web触发立刻执行某个任务

**综上，暂不打算支持此特性**
