### ISSUE TITLE
能否支持crontab 多任务

### ISSUE THREAD

**Issue by wangrui1573** [Akimio521/AutoFilm#50]
比如 
周一到周五 17-20点执行
周末  08-23点执行

0 11-20 * * 1-5 
0 9-23 * * 0

**Comment by Akimio521** [comment]
建议填写两个配置，一个0 11-20 * * 1-5，另一个0 9-23 * * 0

**Comment by wangrui1573** [comment]
类似这样：

Alist2StrmList:
  - id: 任务1                          # 标识 ID
    cron: 30 9-23 * * 1-5                  # 后台定时任务 Crontable 表达式
    url: http://192.168.31.192:5678    # Alist 服务器地址
    username: guest                   # Alist 用户名
    password: guest_Api789             # Alist 密码
    source_dir: /aliyun/Emby/            # Alist 服务器上文件夹路径
    target_dir: /volume2/电影/strm     # 输出路径
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: True                   # 是否下载字幕文件（可选，默认 False）
    image: True                      # 是否下载图片文件（可选，默认 False）
    nfo: True                        # 是否下载 .nfo 文件（可选，默认 False）
    raw_url: False                    # 是否使用原始地址替换 Alist 服务器下载地址（可选，默认 False）
    overwrite: True                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 5                    # 下载文件最大并发数（可选，默认 5）
  - id: 任务2                          # 标识 ID
    cron: 30 9-23 * * 0                  # 后台定时任务 Crontable 表达式
    url: http://192.168.31.192:5678    # Alist 服务器地址
    username: guest                   # Alist 用户名
    password: guest_Api789             # Alist 密码
    source_dir: /aliyun/Emby/            # Alist 服务器上文件夹路径
    target_dir: /volume2/电影/strm     # 输出路径
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: True                   # 是否下载字幕文件（可选，默认 False）
    image: True                      # 是否下载图片文件（可选，默认 False）
    nfo: True                        # 是否下载 .nfo 文件（可选，默认 False）
    raw_url: False                    # 是否使用原始地址替换 Alist 服务器下载地址（可选，默认 False）
    overwrite: True                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 5                    # 下载文件最大并发数（可选，默认 5）
