### ISSUE TITLE
说明中的原版 Jellyfin需修改前端

### ISSUE THREAD

**Issue by cgkings** [Akimio521/AutoFilm#51]
说明中：原版 Jellyfin 开启转码后会代理访问 strm 文件，无法实现直链访问，需修改前端
具体jellyfin应该怎么修改前端或者有已经修改过的jellyfin docker版本推荐吗

**Comment by Akimio521** [comment]
看Jellyfin/Emby的官方API，大致思路是客户端先链接你写的一个前端（反代）程序，然后拿着客户端请求的资源去问上游的Jellyfin/Emby程序得到视频/Strm文件，如果是视频文件就原封转发给客户端，如果是Strm，就返回一个302重定向的地址给客户端（Alist的直链下载地址），客户端拿到这个Alist的直链地址就会访问Alist，如果Alist配置的重定向，就会将上游网盘的CDN地址重新302重定向返回给客户端，这时就实现了流量不经过Alist和Jellyfin/Emby服务器，如果Alist配置的是本机代理，那么流量只会经过Alist服务器

**Comment by Akimio521** [comment]
可以试试[MediaWarp](https://github.com/Akimio521/MediaWarp/)，目前在EmbyServer上使用体验良好，Jellyfin未测试

**Comment by zzzop** [comment]
测试配置选项`mode: AlistURL`
alist存储设置`302重定向`
流量可以不经过Alist和Jellyfin服务器
