### ISSUE TITLE
创建strm和下载个别文件时异常，且为固定几个文件异常

### ISSUE THREAD

**Issue by a1532002280** [Akimio521/AutoFilm#52]
首先万分感谢大佬这个项目，简化了302的步骤，让我这个小白用emby+alist+autofilm就实现了strm直接302播放。

但我从一开始使用(v1.1.2)到现版本(v1.2.3)，都出现了某些视频生成的strm异常，下载的图片和nfo文件损坏的情况，导致strm无法播放，而且比较奇怪的是损坏的为固定的几个文件夹中的所有文件，具体情况如下：
1、已经确认115内文件完整，可在线播放也可下载到本地查看，云端与下载到本地打开均无问题；
2、在alist中确定文件完整，且所有加密均未开启(查看过之前的issue，关闭了加密)，可在线播放也可下载到本地查看，云端与下载到本地打开均无问题；
3、alist和autofilm两个镜像均尝试过重新拉取镜像进行重新部署，配置也是重新设置的，但还是会出现文件损坏问题；
4、没有找到具体的文件损坏的规律，但是能确定的是每次损坏都是固定几个文件夹内的全部文件。

尝试过如下操作，均未解决，且每次尝试均为固定的几个文件内损坏，其他文件无异常：
①在文件第一次异常之后，将所有异常文件删除后，仅重新运行任务，重新下载后的文件仍然异常；
②在文件异常之后，将所有异常文件删除后，重新部署docker并配置(配置文件及媒体目录使用原路径)，重新下载后文件仍异常；
③在文件异常之后，将所有异常文件删除后，重新部署docker并配置(配置及媒体目录均使用新路径)，重新下载后文件仍异常；
④115重新转存此文件，并重新部署alist和autofilm，重新下载后文件仍异常；
四次尝试，容器均无异常，日志未显示错误信息。

目前我115中有3000个视频，只有这几个视频是异常的。经过几次的尝试，我实在是分析不出来是什么原因导致的文件异常，还请大佬帮忙分析一下，下面是一些截图帮助大佬理解问题情况。
![1](https://github.com/user-attachments/assets/e81bdb82-8209-40b1-ab98-7d002c34ee3d)
![2](https://github.com/user-attachments/assets/5d33b67d-c344-4708-b606-c349028b54bc)
![3](https://github.com/user-attachments/assets/b8671dc9-65dc-4268-bb54-e819452d507f)
![4](https://github.com/user-attachments/assets/3aff9df1-c9c8-4f19-9f16-f83eb771a9a6)
![5](https://github.com/user-attachments/assets/88d7e615-d2ea-456a-806a-c3806b7acefe)

**Comment by Akimio521** [comment]
感谢提供详细信息

1. 将异常视频下载到本地是通过Alist下载还是通过115网盘的客户端下载
    1. 尝试浏览器直接打开Strm文件下载到本地后视频是否正常
2. Alist是否启用签名应该不影响
3. 文件异常指的是`nfo`、`png`等文件还是`strm`文件

**Comment by a1532002280** [comment]
> 感谢提供详细信息
> 
> 1. 将异常视频下载到本地是通过Alist下载还是通过115网盘的客户端下载
>    
>    1. 尝试浏览器直接打开Strm文件下载到本地后视频是否正常
> 2. Alist是否启用签名应该不影响
> 3. 文件异常指的是`nfo`、`png`等文件还是`strm`文件

感谢大佬回复！
关于异常的视频：
1、alist只在win11下试过用两个工具下载，idm和aria2，两个工具下载的视频都可以正常播放；
2、115在前几天用PC客户端下过，刚才我又用115浏览器重新下载，两种方式下载都没有问题，下载到本地之后可以正常播放；

我遇到的情况是`nfo`、`jpg`、`strm`这三类文件都有问题，而且一但出问题，那么这三种文件肯定是同时出现问题，且为同一目录(同一个视频)下的文件，比如示例中“YRH-326”的三种文件`错误文件类型数:全部文件类型数`为3:3。不会出现某个视频的`错误:全部`为1:3或2:3的情况。
下面我把这三种文件的异常情况说明一下：
①图片文件：我刮削下的都是`JPG`格式，这些图片经过autofilm下载后体积变小，打开后显示文件损坏。示意图如下：
![图片](https://github.com/user-attachments/assets/65ac3729-bf79-44f3-a56c-7b07624097ce)

②`nfo`文件：`nfo`文件由autofilm下载后，文件内数据被删减，原文件有70多行内容，下载后仅剩下12行。示意图如下：
![nfo](https://github.com/user-attachments/assets/3a8e71c7-de11-4bdc-b18b-0aaf7f3f00a8)

③`strm`文件：`strm`文件无法正常播放，我按照您的提示，试出来两种错误情况
i.在emby客户端内直接打开异常的`strm`，错误截图如下，图片右下角为复制出来的错误信息：
![emby客户端播放](https://github.com/user-attachments/assets/3f82518b-a301-4f15-8c99-d3fdc1e8edf6)

ii.从浏览器中直接下载strm文件，使用播放器直接打开，错误截图如下，右侧为复制出来的错误信息：
![strm文件](https://github.com/user-attachments/assets/ef055bd9-933b-4432-90a4-d22dd8f88936)

我不知道我表述的是否清楚，如有表达不清或缺漏的地方还请您指出，我会尽快回复

**Comment by a1532002280** [comment]
> 1. 如果可以浏览器访问`192.168.66.3"5244/d/xxxxxxx`可以正确跳转到下载界面说明本项目功能是正常的，应该是Alist方面的问题，本项目对Strm文件的处理仅限于拼接字符串，使其Strm文件内容是Alist服务器上文件的下载地址
> 2. 如果`jpg`、`nfo`文件有损坏应该是上游网盘限制了并发数，在`v1.2.3`可以通过`max_workers`控制下载文件的并发量、在目前最新的DEV版本中`max_workers`被修改成访问Alist服务器的部分数量，而下载文件的并发数量被修改成了`max_downloaders`（目前已提交版本是max_downloader，后续会修改名字），可以尝试修改这两个变量控制并发数，115网盘我不太清楚，阿里云限制明确限制的API对网盘的并发请求量，如果是`jpg`、`nfo`等下载文件有问题可以适当减小同时下载文件的数量

大佬 异常解决了，将`异常文件`所在的`文件夹`进行重命名即可解决此问题。但是我没有搞明白具体原因，只能写一下我的使用情况及一些推测：

首先我是用`mdcx`刮削视频，刮削成功后重命名所有文件，并且在115中新建并重命名文件夹，将所有文件移动过去；然后`alist`隔段时间刷新缓存，同步115；最后`autofilm`根据`alist`的文件目录进行创建strm、jpg和nfo文件。

在整个流程中，这三个过程或两个过程有概率同时运行：①`mdcx`刮削后移动文件到新文件夹②`alist`在刷新缓存以同步115中新建的文件夹③`autofilm`正在运行，创建strm及下载nfo等文件。

我猜测是③运行过程中，②突然运行导致了异常；也有可能是①②③同时运行到新创建的文件夹，导致异常。虽然概率小(0.6%)，但确实可能发生。
### 下面是具体的测试情况，供您查阅分析：

1、重新拉取`dev`版本镜像，并把`max_workers`改为了10，`max_downloaders`改为了1，重新执行创建strm任务。最后发现还是那些文件异常，并且异常的情况与之前提到的一样，应该是排除了网盘并发这个因素。
2、我把异常的strm文件(包含`dev`、`v1.2.3`两个版本创建的strm)打开后，把里面的地址粘贴到浏览器进行访问，均显示错误
`{
    "code": 500,
    "message": "failed link: failed to get file: object not found",
    "data": null
}`

查询得知异常原因为`错误的原因是尝试获取一个文件时，发现该文件不存在（"object not found"）`后，我打开alist和115网盘进行查看，发现文件是确实存在的，猜测是否因为文件夹名称中存在日文或者某些特殊字符导致查找不到文件，无法下载；然后使用其他正常strm文件中的链接进行访问，发现可以正常解析到115的直链进行下载，排除因文件夹名称而导致的问题；
![直链下载](https://github.com/user-attachments/assets/f68cc2ef-8a50-4474-9c75-5ae658621e3e)

3、我使用115网盘将发生异常文件所在的文件夹进行了重命名(文件夹内文件无任何操作)，由`[YRH-326]-XXXXX`更改为`[YRH-326]`(删除了全部日文)，删除本地异常文件，使用本项目重新创建`strm`等文件，所有文件正常，可被emby读取，也可直接打开；
4、使用alist将另一个异常文件夹进行重命名(文件夹内文件无任何操作)，由`[MBDD-2021]-XXXX`更改为`[MBDD-2021]-X`(删除了部分日文)，删除异常文件，使用本项目重新创建`strm`等文件，所有文件正常，可被emby读取，也可直接打开；
![11111](https://github.com/user-attachments/assets/241233b1-7986-49d4-a3f2-b8ee3b955235)
![正常](https://github.com/user-attachments/assets/c54b8a2b-069c-451b-92b4-3f48c91d339d)
最后经过多次测试发现，只需要改动一下出现异常文件所在的文件夹名称即可，增加或删减任意字符都可以解决问题。

**Comment by Akimio521** [comment]
1. `max_downloaders`版本我还未推送，截止至2024-7-27 19:58，仓库中最新的版本采用的命名是`max_downloader`，因此限制最大同时下载的变量`max_downloaders`不生效，但是由于你限制了`max_workers`所以最大同时下载的文件应该是10，影响不大
2. **关于文件不存在**：关于打开Strm文件中的链接却提示文件不存在的情况应该出现概率较小，可以尝试解码url，这样可以看到文件的真实路径，便于判断路径是否正确，[解码在线工具](https://www.toolhelper.cn/EncodeDecode/Url)
3. **关于日文**：Python3默认采用utf-8的编码形式，理论上是支持中文、日文路径的，可以尝试使用上述工具对比路径是否有问题
4. **关于特殊字符**：这个概率偏大，可能是特殊字符导致编码有误，但是考虑到重命名前出错nfo文件前半部分是正常的，说明下载前期正常访问，下载中由于某些缘故导致文件请求出错
5. 关于使用：我个人推荐网盘上仅存放视频文件，将视频生成Strm文件后再进行刮削

**Comment by a1532002280** [comment]
> 1. **关于变量`max_downloaders`**：`max_downloaders`版本我还未推送，截止至2024-7-27 19:58，仓库中最新的版本采用的命名是`max_downloader`，因此限制最大同时下载的变量`max_downloaders`不生效，但是由于你限制了`max_workers`所以最大同时下载的文件应该是10，影响不大
> 2. **关于文件不存在**：关于打开Strm文件中的链接却提示文件不存在的情况应该出现概率较小，可以尝试解码url，这样可以看到文件的真实路径，便于判断路径是否正确，[解码在线工具](https://www.toolhelper.cn/EncodeDecode/Url)
>    
>    1. **关于日文**：Python3默认采用utf-8的编码形式，理论上是支持中文、日文路径的，可以尝试使用上述工具对比路径是否有问题
>    2. **关于特殊字符**：这个概率偏大，可能是特殊字符导致编码有误，但是考虑到重命名前出错nfo文件前半部分是正常的，说明下载前期正常访问，下载中由于某些缘故导致文件请求出错
>    3. 综上，三个软件同时运行造成的错误概率较大
> 3. **关于使用**：我个人推荐网盘上仅存放视频文件，将视频生成Strm文件后再进行刮削，如果想将刮削文件一并存入网盘中，推荐使用AutoFIlm时将Alist的本机代理打开，使用完成后再重新改成302重定向，这样可以减小下载文件的出错概率

感谢大佬解惑！我将错误的strm解码后与alist路径对比，发现路径相同，应该就是三个软件同时运行导致的错误。
目前已经将容器中的程序手动停止，仅在刮削并同步完后开启。
