### ISSUE TITLE
1.2.4版本中，下载的字幕等文件内容异常：{"status":403,"message":"invalid signature","request_id":"***"}

### ISSUE THREAD

**Issue by z-henry** [Akimio521/AutoFilm#60]
`1.2.3`正常，`1.2.4`出问题
mode设置的`AlistURL`
`__file_processer`函数中获取`path.raw_url`来作为下载地址
下载后的ass/nfo/jpg等文件，文件内容异常：{"status":403,"message":"invalid signature","request_id":"***"}
换成`content`后正常
不知道是不是和我alist设置的`本地代理`有关。

**Comment by Akimio521** [comment]
**缺少关键信息**
无论`mode`设置成什么模式都不会影响**文件的下载**
推荐排查方式：分别将`mode`设为`AlistURL`和`RawURL`，浏览器访问Strm文件的内容，如果能正确下载，则与本项目无关

**Comment by z-henry** [comment]
115的直链要做ua验证
建议将mode的作用范围扩大，不仅仅只指定strm中的路径类型，并且也控制下载元数据使用哪种类型的路径
**和1.2.3保持一致**

**Comment by Akimio521** [comment]
没用过115，确实不知道要检测UA，到时候我全部修改成path.download_url作为下载方式，具体下载策略交给Alist实现

**Comment by Akimio521** [comment]
AutoFilm v1.2.4-1已修复
