### ISSUE TITLE
优化建议：当mode为alisturl时，是否可以省略对文件的fs/get操作

### ISSUE THREAD

**Issue by z-henry** [Akimio521/AutoFilm#61]
递归遍历文件夹操作时，如果是文件，会调用一次fs/get操作。
在mode设置为alisturl时，对文件的父目录进行fs/list操作时已经可以获取需要的字段。
我在没启用sign的时候测试，不调用fs/get也不会影响strm生成和元信息的下载。

我是在alist挂载115时发现扫描一遍很慢。经过分析发现是当alist触发了缓存过期之后，所有的alist api都会触发强制刷新，导致需要调用对应的网盘接口，响应速度变慢。
如果文件过多，对于这些文件的get操作会触发风控或者耗时很长。如果能省下这些操作，那么提升会是巨大的。

最后感谢您的项目，对我非常好用，希望它可以变的更好

**Comment by Akimio521** [comment]
那还需要判断是否启用签名

**Comment by z-henry** [comment]
https://alist.nn.ci/zh/guide/api/fs.html#post-%E5%88%97%E5%87%BA%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95
list的返回有sign，但是我没验证过这种情况

**Comment by Akimio521** [comment]
之前我记得是没有sign属性的，也不知道是不是修改了，现在你试试性能有没有提升

**Comment by z-henry** [comment]
iter_path内部递归调用的时候，应该也需要传递is_detail参数

**Comment by Akimio521** [comment]
确实

**Comment by Akimio521** [comment]
若测试无误，将发布一个小版本

**Comment by z-henry** [comment]
alisturl，未启用sign，测试没问题

**Comment by Akimio521** [comment]
最好再试一下开启签名的吧

**Comment by z-henry** [comment]
alisturl，启用sign，测试没问题
