### ISSUE TITLE
AniOpen所有数据同步到alist地址树

### ISSUE THREAD

**Issue by shiji5824666** [Akimio521/AutoFilm#62]
咨询一下，怎么把AniOpen所有数据同步到alist地址树，config.yaml只给出了按时间同步，或者按最新RSS同步

**Comment by Akimio521** [comment]
需要自己写一个脚本，给你一个简单的思路，把Ani2Alist这个类import到脚本中，写一个for循环实例化对象，再调用run方法

**Comment by Akimio521** [comment]
需要自己写一个脚本，给你一个简单的思路，把Ani2Alist这个类import到脚本中，写一个for循环实例化对象，再调用run方法

**Comment by shiji5824666** [comment]
大佬，你的演示站挂掉了，能修复一下吗？

**Comment by Akimio521** [comment]
什么演示站，我只提供了博客作为说明文档，此外我没有提供任何服务
