### ISSUE TITLE
获取目录{dir_path_str}的文件列表的请求超时

### ISSUE THREAD

**Issue by FEOQin** [Akimio521/AutoFilm#63]
执行脚本后提示：
[WARNING]2024-10-03 19:20:03,617 - 获取目录{dir_path_str}的文件列表的请求超时，3秒后重试 ...
[WARNING]2024-10-03 19:25:07,669 - 获取目录{dir_path_str}的文件列表的请求超时，3秒后重试 ...
[WARNING]2024-10-03 19:25:10,703 - 获取目录{dir_path_str}的文件列表的请求超时，超出最大重试次数！
[INFO]2024-10-03 19:25:10,711 - Alist2Strm处理完成

似乎是连接问题。
使用alist默认的 url: http://localhost:5244 是可以生成 .strm 文件的。但是现在我使用了一个加密项目 alist-encrypt 对 alist 提供 webdav 的加解密功能。支持 alist 网页在线播放加密的视频，查看加密的图片等功能，同时在 webdav 下的操作透明，自动实现文件资源的加解密。这个项目对alist进行了代理 url: http://localhost:5344 ，我把 config.yaml 的 url 替换成 5344 ，便会报错。
项目地址：https://github.com/traceless/alist-encrypt

**Comment by Akimio521** [comment]
先确认该项目是否支持Alist相关API操作

**Comment by FEOQin** [comment]
不懂哈哈。问项目作者说支持，可以把他理解为就是一个nginx。这个项目本身5344端口就是alist，可以操作alist所有的功能，复制、上传、添加存储什么的。
在另一个给alist生成strm的项目：https://github.com/tefuirZ/alist-strm 中是可以识别它5344的端口的。

**Comment by Akimio521** [comment]
你先下载最新的源码或者使用DEV标签的镜像重新运行一下，看看日志
