### ISSUE TITLE
开启emby，将媒体图像保存到媒体文件夹中后，造成emby 反复削刮，strm自动删除循环中

### ISSUE THREAD

**Issue by wangrui1573** [Akimio521/AutoFilm#67]
autofilm似乎会自动删除 alist中没有，而本地有的文件，比如本地削刮的海报文件，nfo文件
就会造成 造成emby 反复削刮，strm自动循环删除
这个功能有开关吗？

[INFO]2024-10-15 15:17:30,674 - 删除文件：/volume2/电影/strm/real/Emby/电影/暗杀风暴 (2023)/poster.jpg

[INFO]2024-10-15 15:17:30,675 - 删除文件：/volume2/电影/strm/real/Emby/电影/但愿人长久 (2024)/poster.jpg

[INFO]2024-10-15 15:17:30,675 - 删除文件：/volume2/电影/strm/real/Emby/电影/怒潮 (2023)/poster.jpg

[INFO]2024-10-15 15:17:30,676 - 删除文件：/volume2/电影/strm/real/Emby/电影/周处除三害 (2023)/fanart.jpg

[INFO]2024-10-15 15:17:30,677 - 删除文件：/volume2/电影/strm/real/Emby/电视剧/边水往事 (2024)/S01E14.2024.2160p.WEB-DL.DDP2.0.H265.60fps.nfo

[INFO]2024-10-15 15:17:30,677 - 删除文件：/volume2/电影/strm/real/Emby/电影/宇宙探索编辑部 (2023)/poster.jpg

[INFO]2024-10-15 15:17:30,678 - 删除文件：/volume2/电影/strm/real/Emby/电影/热辣滚烫 (2024)/热辣滚烫.2024.1080p.WEB-DL.AAC.H.264.nfo

[INFO]2024-10-15 15:17:30,678 - 删除文件：/volume2/电影/strm/real/Emby/电影/潜行 (2023)/poster.jpg

[INFO]2024-10-15 15:17:30,679 - 删除文件：/volume2/电影/strm/real/Emby/电影/拯救嫌疑人 (2023)/poster.jpg

[INFO]2024-10-15 15:17:30,679 - 删除文件：/volume2/电影/strm/real/Emby/电影/首尔之春 (2023)/poster.jpg

[INFO]2024-10-15 15:17:30,680 - 删除文件：/volume2/电影/strm/real/Emby/电影/临时劫案 (2024)/clearlogo.png

[INFO]2024-10-15 15:17:30,681 - 删除文件：/volume2/电影/strm/real/Emby/电影/犯罪都市4 (2024)/The Roundup Punishment.2024.1080p.WEB-DL.AAC2.0.H.264-TIK.nfo

[INFO]2024-10-15 15:17:30,681 - 删除文件：/volume2/电影/strm/real/Emby/电影/犯罪都市3 (2023)/poster.jpg

[INFO]2024-10-15 15:17:30,682 - 清理过期的 .strm 文件完成

**Comment by Akimio521** [comment]
如果是自行拉取最新main分支运行的话，需要将sync_server设为False #65

**Comment by wangrui1573** [comment]
从开发版dev本，退回到 latest 后正常，另外dev版 输出路径 会输出alist完整路径，不会省略配置的alist前缀

**Comment by Akimio521** [comment]
> 输出路径 会输出alist完整路径，不会省略配置的alist前缀

没理解你在说什么
