### ISSUE TITLE
对接Alist 115风控有点严重 挂了一天后 第二天开始无限制风控，并发和同时下载全部改成1了

### ISSUE THREAD

**Issue by sleikang** [Akimio521/AutoFilm#70]
![image](https://github.com/user-attachments/assets/3d57a1b3-4bc0-4cf8-9455-5fa94f6fa1d6)

**Comment by Akimio521** [comment]
直接在alist的web可以正常使用吗

**Comment by sleikang** [comment]
> 直接在alist的web可以正常使用吗

之前我是alist rclone挂载磁盘让emby扫盘都不会风控，现在这个项目一扫目录就风控了，每次风控alist只能重新登陆115 估计是频率太快了，网盘接口请求是有频率限制的，估计得改进扫描目录树的方式

**Comment by Akimio521** [comment]
不定因素太多，没办法复现，我也没遇到这样的问题，有能力建议直接提交pr

**Comment by sleikang** [comment]
> 不定因素太多，没办法复现，我也没遇到这样的问题，有能力建议直接提交pr

没法复现可能是你文件太少了我115 近60T的资源，我挂你这个也是第一天没有风控 第二天115就把我的号拉到风险账号了 一开就风控现在不敢弄这个玩意儿了，现在持续高风险中 稍微手动访问快点就被风控只能重新提CK

**Comment by Akimio521** [comment]
v1.2.4-1中已经尽力减少api的请求，目前对于非RawURL模式的请求仅限于递归查询目录下有哪些文件，并不会像旧版不断请求下载URL

对于多资源来说，你的60T会每天都有变化吗，每天新增资源肯定不会超过500G，又不是不能拆分成多个目录，长期资源可以设置3个月扫描一次，追新资源可以设置成7天扫描一次

**Comment by mapleshadow** [comment]
设置分页1500，限制速率4，再看看？
